version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-dumps/pg:/var/lib/postgresql/data

  server:
    depends_on:
      - 'db'
    volumes:
      - ./server:/app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5000
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=passu
      - PGDATABASE=my_db
